"""Core online step-by-step routing engine.

Reasoning trajectory format:
    <think>
    step 1 reasoning...

    step 2 reasoning...
    </think>

    The answer is $\\boxed{answer}$.

Rules:
    - Steps inside <think> are separated by \\n\\n
    - Answer (after </think>) is ALWAYS generated by LRM
    - Each step can be generated by SRM or LRM via continue_final_message
    - For TRIM-style routing: SRM generates first, then router decides
      whether to replace with LRM
    - For random routing: randomly pick SRM or LRM per step
"""

import time
from typing import Callable, Dict, List, Optional

import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from common.config import (
    SRM_URL, LRM_URL, SRM_PARAMS_B, LRM_PARAMS_B,
    SYSTEM_PROMPT, MAX_STEPS, MAX_TOKENS_PER_STEP, MAX_ANSWER_TOKENS,
)
from common.llm import call_model
from common.answer import extract_answer, check_correctness


def _build_messages(problem: str, accumulated: str, system_prompt: str = SYSTEM_PROMPT):
    return [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": problem},
        {"role": "assistant", "content": accumulated},
    ]


def _generate_step(url: str, messages: list, max_tokens: int = MAX_TOKENS_PER_STEP) -> Dict:
    """Generate one reasoning step via continuation, stopped at \\n\\n."""
    result = call_model(
        url, messages,
        max_tokens=max_tokens,
        temperature=0.7,
        stop=["\n\n"],
        think_mode=True,
        continue_final=True,
        timeout=300,
    )
    return result


def online_route(
    problem: str,
    ground_truth: str,
    router_fn: Callable,
    router_name: str = "custom",
    system_prompt: str = SYSTEM_PROMPT,
    max_steps: int = MAX_STEPS,
) -> Dict:
    """Run online step-by-step routing on a single problem.

    Args:
        problem: The math problem text.
        ground_truth: The correct answer string.
        router_fn: Callable(step_idx, srm_step_text, step_history) -> bool.
                   Returns True to use LRM, False to keep SRM.
        router_name: Name of the routing strategy (for logging).
        system_prompt: System prompt for the model.
        max_steps: Maximum number of reasoning steps.

    Returns:
        Dict with full trajectory, answer, correctness, costs, etc.
    """
    accumulated = "<think>\n"
    steps = []
    srm_tokens = 0
    lrm_tokens = 0
    srm_time = 0.0
    lrm_time = 0.0
    think_ended = False

    for step_idx in range(max_steps):
        msgs = _build_messages(problem, accumulated, system_prompt)

        # SRM generates next step (stopped at \n\n by vLLM)
        srm_result = _generate_step(SRM_URL, msgs)
        srm_step = srm_result["content"]
        srm_tokens += srm_result["tokens"]
        srm_time += srm_result["elapsed"]

        # Router decides
        use_lrm = router_fn(step_idx, srm_step, steps)

        if use_lrm:
            lrm_result = _generate_step(LRM_URL, msgs)
            lrm_step = lrm_result["content"]
            lrm_tokens += lrm_result["tokens"]
            lrm_time += lrm_result["elapsed"]
            chosen_step = lrm_step
            chosen_model = "LRM"
        else:
            chosen_step = srm_step
            chosen_model = "SRM"

        # If </think> appeared in generated text, trim and stop thinking
        has_think_end = "</think>" in chosen_step
        if has_think_end:
            idx = chosen_step.index("</think>")
            chosen_step = chosen_step[:idx + len("</think>")]

        steps.append({
            "idx": step_idx,
            "model": chosen_model,
            "text": chosen_step,
            "srm_text": srm_step,
        })

        if has_think_end:
            accumulated += chosen_step
            think_ended = True
            break
        else:
            accumulated += chosen_step + "\n\n"

    if not think_ended:
        accumulated += "\n</think>"

    # Answer phase: always LRM
    ans_msgs = _build_messages(problem, accumulated + "\n\n", system_prompt)
    ans_result = call_model(
        LRM_URL, ans_msgs,
        max_tokens=MAX_ANSWER_TOKENS,
        temperature=0.0,
        think_mode=True,
        continue_final=True,
        timeout=300,
    )
    answer_text = ans_result["content"]
    lrm_tokens += ans_result["tokens"]
    lrm_time += ans_result["elapsed"]

    full_text = accumulated + "\n\n" + answer_text

    pred = extract_answer(full_text)
    is_correct = check_correctness(pred, ground_truth)

    srm_flops = 2 * SRM_PARAMS_B * srm_tokens
    lrm_flops = 2 * LRM_PARAMS_B * lrm_tokens
    total_flops = srm_flops + lrm_flops

    n_lrm_steps = sum(1 for s in steps if s["model"] == "LRM")
    n_total_steps = len(steps)
    regen_ratio = n_lrm_steps / n_total_steps if n_total_steps > 0 else 0
    # Cost percentage relative to LRM-only (approximate)
    lrm_only_flops = 2 * LRM_PARAMS_B * (srm_tokens + lrm_tokens)
    cpt = total_flops / lrm_only_flops * 100 if lrm_only_flops > 0 else 100

    return {
        "full_text": full_text,
        "predicted": pred,
        "ground_truth": ground_truth,
        "is_correct": is_correct,
        "steps": steps,
        "n_steps": n_total_steps,
        "n_lrm_steps": n_lrm_steps,
        "regen_ratio": round(regen_ratio, 4),
        "srm_tokens": srm_tokens,
        "lrm_tokens": lrm_tokens,
        "srm_flops": round(srm_flops, 1),
        "lrm_flops": round(lrm_flops, 1),
        "total_flops": round(total_flops, 1),
        "cpt": round(cpt, 2),
        "srm_time": round(srm_time, 2),
        "lrm_time": round(lrm_time, 2),
        "router": router_name,
    }
